export { default as LogoImage } from './vercel.svg'
export { default as HeadlineImage } from './headline.bw.jpg'
export { default as CoverImage } from './cover.jpg'
export { default as Pyconit } from './pyconit.svg'
export { default as Workingsoftware } from './workingsoftware.svg'
