import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import styled from 'styled-components'
import useGeolocation from '../hooks/useGeolocation'

const Header = styled.nav`
  display: flex;
  align-items: center;
  justify-content: space-between;
`

const Home: NextPage = () => {
  const { country } = useGeolocation()
  const router = useRouter()
  if (country && country !== 'it') {
    router.push('/en')
    return <></>
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header>
          <h1>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
        </Header>

        <p>Hello world</p>
      </main>
      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer">
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} unoptimized={true} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
